import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "@/style/globals.css";
import { ThemeProvider } from '@/components/providers/theme-provider';
import { Toaster } from "@/components/ui/sonner"
import { SocketProvider } from "@/components/providers/socket-provider";
import { AuthSessionProvider } from "@/components/providers/auth-provider";
import { server_auth } from "./(auth)/auth";
import { ProgressBar } from "@/components/layout/header/ProgressBar";
import { UIProviders } from "@/components/providers/HeroUIProvider";
import { DebugPanel } from "@/components/common/debug-panel";
import { StyleContextProvider } from "@/components/context/styleContext";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default: 'mcc',
    template: '%s | mcc',
  },
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await server_auth();
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          // defaultTheme="light"
          enableSystem={false}
          // enableSystem
          disableTransitionOnChange
        >
          <StyleContextProvider>
          <UIProviders>
          <AuthSessionProvider session={session}>
            <SocketProvider>
              <ProgressBar />
              {children}
            </SocketProvider>
          </AuthSessionProvider>
          </UIProviders>
          <DebugPanel />
          </StyleContextProvider>
          <Toaster position="top-right" richColors   />
        </ThemeProvider>
      </body>
    </html>
  );
}
